require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/carstatuses", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Carstatus. As you add validations to Carstatus, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Carstatus.create! valid_attributes
      get carstatuses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      carstatus = Carstatus.create! valid_attributes
      get carstatus_url(carstatus)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_carstatus_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      carstatus = Carstatus.create! valid_attributes
      get edit_carstatus_url(carstatus)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Carstatus" do
        expect {
          post carstatuses_url, params: { carstatus: valid_attributes }
        }.to change(Carstatus, :count).by(1)
      end

      it "redirects to the created carstatus" do
        post carstatuses_url, params: { carstatus: valid_attributes }
        expect(response).to redirect_to(carstatus_url(Carstatus.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Carstatus" do
        expect {
          post carstatuses_url, params: { carstatus: invalid_attributes }
        }.to change(Carstatus, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post carstatuses_url, params: { carstatus: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested carstatus" do
        carstatus = Carstatus.create! valid_attributes
        patch carstatus_url(carstatus), params: { carstatus: new_attributes }
        carstatus.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the carstatus" do
        carstatus = Carstatus.create! valid_attributes
        patch carstatus_url(carstatus), params: { carstatus: new_attributes }
        carstatus.reload
        expect(response).to redirect_to(carstatus_url(carstatus))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        carstatus = Carstatus.create! valid_attributes
        patch carstatus_url(carstatus), params: { carstatus: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested carstatus" do
      carstatus = Carstatus.create! valid_attributes
      expect {
        delete carstatus_url(carstatus)
      }.to change(Carstatus, :count).by(-1)
    end

    it "redirects to the carstatuses list" do
      carstatus = Carstatus.create! valid_attributes
      delete carstatus_url(carstatus)
      expect(response).to redirect_to(carstatuses_url)
    end
  end
end
